Controllers/ClienteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CriptoFinanceiraWeb.Models;
using CriptoFinanceiraWeb.DAL;

namespace CriptoFinanceiraWeb.Controllers
{
    public class ClienteController : Controller
    {
        // GET: Cliente
        public ActionResult MenuCliente(LoginModel login)
        {
            

            String aux = "";
            String auxCarteira = "";
            String auxOrdens = "";

 //           if (login.chave_cliente != null){
 //               int index = login.chave_cliente.IndexOf(" ");
 //               int aux1 = index - 2;
 //               aux = login.chave_cliente.Substring(3, aux1);
 //           }
 //           else
            
                aux = Session["Nome"].ToString().Substring(3, Session["Nome"].ToString().IndexOf(" ") - 2);
                auxCarteira = "R$ " + Session["Carteira"].ToString();
                auxOrdens = "R$ " + Session["Ordens"].ToString();

                ViewBag.nomeCliente = "Olá, " + aux + "!";
                ViewBag.saldoCarteira = auxCarteira;
                ViewBag.saldoOrdens = auxOrdens;

            return View();
        }

        public ActionResult Comprar(LoginModel login)
        {

            return View();
        }

        public ActionResult Vender(LoginModel login)
        {
            return View();
        }

        public ActionResult Depositar(LoginModel login)
        {
            return View();
        }

        public ActionResult Transferir(LoginModel login)
        {
            return View();
        }

        [HttpPost]
        public ActionResult ComprarMoeda()
        {
            String moeda = Request["select"].Substring(0, Request["select"].IndexOf(")")) + ")";
            String quantidade = Request["quantidade"];

            ClientesDao cliente = new ClientesDao();
            if(cliente.comprarMoeda(moeda, quantidade, Session["Nome"].ToString()))
            {
                ViewBag.mensagemCompra = cliente.mensagem;
            }
            else
            {
                ViewBag.mensagemErro = cliente.mensagem;
                
            }
            return View("Comprar");
        }

        [HttpPost]
        public ActionResult VenderMoeda()
        {
            String moeda = Request["select"].Substring(0, Request["select"].IndexOf(")")) + ")";
            String quantidade = Request["quantidade"];

            ClientesDao cliente = new ClientesDao();
            if (cliente.comprarMoeda(moeda, quantidade, Session["Nome"].ToString()))
            {
                ViewBag.mensagemCompra = cliente.mensagem;
            }
            else
            {
                ViewBag.mensagemErro = cliente.mensagem;

            }
            return View("Vender");
        }
    }
}

Views/Shared/_ClienteLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Cripto Financeira S/A</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @model CriptoFinanceiraWeb.Models.LoginModel
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <a class="navbar-brand"><img src="~/Imagens/cripto.png" /></a>
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Cripto Financeira", "MenuCliente", "Cliente", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Comprar", "Comprar", "Cliente", Model)</li>
                    <li>@Html.ActionLink("Vender", "Vender", "Cliente", Model)</li>
                    <li>@Html.ActionLink("Depositar", "Depositar", "Cliente", Model)</li>
                    <li>@Html.ActionLink("Transferir", "Transferir", "Cliente", Model)</li>
                </ul>
                <ul class="nav navbar-nav navbar-right">

                    <li>@Html.ActionLink("Logoff", "Index", "Home") </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p style="color: mediumaquamarine;">&copy; @DateTime.Now.Year - Cripto Financeira S/A</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Cripto Financeira S/A</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <a class="navbar-brand"><img src="~/Imagens/cripto.png" /></a>
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Cripto Financeira", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Cadastro", "Cadastro", "Cadastro")</li>
                    <li>@Html.ActionLink("Sobre Nós", "About", "Home")</li>
                </ul>
                <ul class="nav navbar-nav navbar-right">

                    <li>@Html.ActionLink("Login", "Login", "Login") </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p style="color: mediumaquamarine;">&copy; @DateTime.Now.Year - Cripto Financeira S/A</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>